log:
  file: opulence-engine.log
  debug: True

engine:
  celery_request_timeout: 2

  databases:
    queue_database:
      broker_url: redis://redis/1
      result_backend: redis://redis/1

    mongoDB:
        database: opulence
        url: mongodb://mongo:27017/
        connect_timeout: 3


remote_collectors:
  queue_database:
    broker_url: redis://redis/0
    result_backend: redis://redis/0
