
default:
  CELERY_TIMEOUT: 2
  REDIS:
      broker_url: redis://localhost/0
      result_backend: redis://localhost/0
  MONGO:
        database: opulence
        url: mongodb://localhost/
        connect_timeout: 3

  REMOTE_COLLECTOR:
    redis:
      broker_url: redis://localhost/0
      result_backend: redis://localhost/0

development:
  DEBUG: true
