
default:
  CELERY_TIMEOUT: 2
  REDIS:
      broker_url: redis://:thisisaverrygoodpassword@redis/1
      result_backend: redis://:thisisaverrygoodpassword@redis/1
  MONGO:
        database: opulence
        url: mongodb://mongo:27017/
        connect_timeout: 3

  REMOTE_COLLECTOR:
    redis:
      broker_url: redis://:thisisaverrygoodpassword@redis/0
      result_backend: redis://:thisisaverrygoodpassword@redis/0

development:
  DEBUG: true

production:
  DEBUG: false
